on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: "kitta65/dotfiles"
      CHECKOUT_BRANCH: "main"
      PR_AGAINST_BRANCH: "main"
      OWNER: "kitta65"

    steps:
      - uses: actions/checkout@v2
      - id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.RELEASE_HUB_SECRET }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}
